import { Shield, Lock, Scale, Image as ImageIcon, Server, AlertTriangle } from "lucide-react"
import LegalContent, { LegalSection } from "@/components/legal-content"

export default function TermsPage() {
  return (
    <LegalContent title="Terms & Conditions">
      <div className="space-y-8">
        <p>
          Welcome to MaskingTech ("we", "our", or "us"). By accessing or using our platform, website,
          or services, you agree to comply with and be bound by these Terms and Conditions. If you
          do not agree, please do not use our services.
        </p>

        <LegalSection title="1. Services" icon={<Server className="h-5 w-5" />}>
          <p>
            MaskingTech provides AI-powered tools for automotive image processing, including but not
            limited to license plate masking, face blurring, background replacement, and dent/scratch
            detection. These services are intended for lawful and professional use.
          </p>
        </LegalSection>

        <LegalSection title="2. User Responsibilities" icon={<Shield className="h-5 w-5" />}>
          <p>
            Users are responsible for ensuring that any images or data uploaded to MaskingTech are
            lawful and do not infringe the rights of any third party. You agree not to use the platform for
            illegal, unethical, or harmful purposes.
          </p>
        </LegalSection>

        <LegalSection title="3. Intellectual Property" icon={<Scale className="h-5 w-5" />}>
          <p>
            All technology, content, and intellectual property associated with MaskingTech remain our
            exclusive property.
            Users are granted a limited, non-exclusive license to use the platform for its intended
            purpose only.
          </p>
        </LegalSection>

        <LegalSection title="4. Account & Access" icon={<Lock className="h-5 w-5" />}>
          <p>
            You may be required to create an account to access certain features. You are responsible for
            maintaining the confidentiality of your account credentials and for all activities that occur
            under your account.
          </p>
        </LegalSection>

        <LegalSection title="5. Payments & Credits" icon={<Server className="h-5 w-5" />}>
          <p>
            MaskingTech operates on a credit-based or subscription model. All payments are non-
            refundable unless otherwise stated. Credits may expire if unused within the specified
            period, and misuse of credits may lead to account suspension.
          </p>
        </LegalSection>

        <LegalSection title="6. Limitation of Liability" icon={<AlertTriangle className="h-5 w-5" />}>
          <p>
            MaskingTech is not liable for any direct, indirect, or consequential damages resulting from
            your use of the platform. All outputs are generated by AI and provided "as is." Users must
            verify results before commercial use.
          </p>
        </LegalSection>

        <LegalSection title="7. Modifications" icon={<ImageIcon className="h-5 w-5" />}>
          <p>
            We may update or modify these Terms at any time. Continued use of the service constitutes
            acceptance of the updated Terms.
          </p>
        </LegalSection>

        <LegalSection title="8. Governing Law" icon={<Scale className="h-5 w-5" />}>
          <p>
            These Terms are governed by the laws of the United Arab Emirates. Any disputes shall be
            resolved in the competent courts of Ras Al Khaimah.
          </p>
        </LegalSection>
      </div>
    </LegalContent>
  )
} 